<?php

return [
    'active' => [
        // Layout
        'aspect-ratio'               => true,
        'columns'                    => true,
        'break-after'                => true,
        'break-before'               => true,
        'break-inside'               => true,
        'box-decoration-break'       => true,
        'box-sizing'                 => true,
        'display'                    => true,
        'float'                      => true,
        'clear'                      => true,
        'isolation'                  => true,
        'object-fit'                 => true,
        'object-position'            => true,
        'overflow'                   => true,
        'overscroll-behavior'        => true,
        'position'                   => true,
        'top-right-bottom-left'      => true,
        'visibility'                 => true,
        'z-index'                    => true,
        // Flexbox & Grid
        'flex-basis'                 => true,
        'flex-direction'             => true,
        'flex-wrap'                  => true,
        'flex'                       => true,
        'flex-grow'                  => true,
        'flex-shrink'                => true,
        'order'                      => true,
        'grid-template-columns'      => true,
        'grid-column'                => true,
        'grid-template-rows'         => true,
        'grid-row'                   => true,
        'grid-auto-flow'             => true,
        'grid-auto-columns'          => true,
        'grid-auto-rows'             => true,
        'gap'                        => true,
        'justify-content'            => true,
        'justify-items'              => true,
        'justify-self'               => true,
        'align-content'              => true,
        'align-items'                => true,
        'align-self'                 => true,
        'place-content'              => true,
        'place-items'                => true,
        'place-self'                 => true,
        // Spacing
        'padding'                    => true,
        'margin'                     => true,
        'space'                      => true,
        // Sizing
        'width'                      => true,
        'min-width'                  => true,
        'max-width'                  => true,
        'height'                     => true,
        'min-height'                 => true,
        'max-height'                 => true,
        // Typography
        'font-family'                => true,
        'font-size'                  => true,
        'font-smoothing'             => true,
        'font-style'                 => true,
        'font-weight'                => true,
        'font-variant-numeric'       => true,
        'letter-spacing'             => true,
        'line-height'                => true,
        'list-style-type'            => true,
        'list-style-position'        => true,
        'text-align'                 => true,
        'text-color'                 => true,
        'text-decoration'            => true,
        'text-decoration-color'      => true,
        'text-decoration-style'      => true,
        'text-decoration-thickness'  => true,
        'text-underline-offset'      => true,
        'text-transform'             => true,
        'text-overflow'              => true,
        'text-indent'                => true,
        'vertical-align'             => true,
        'whitespace'                 => true,
        'word-break'                 => true,
        // Backgrounds
        'content'                    => true,
        'background-attachment'      => true,
        'background-clip'            => true,
        'background-color'           => true,
        'background-origin'          => true,
        'background-position'        => true,
        'background-repeat'          => true,
        'background-size'            => true,
        'background-image'           => true,
        'gradient-color-stops'       => true,
        'border-radius'              => true,
        'border-width'               => true,
        'border-color'               => true,
        'border-style'               => true,
        'divide-width'               => true,
        'divide-color'               => true,
        'divide-style'               => true,
        'outline-width'              => true,
        'outline-color'              => true,
        'outline-style'              => true,
        'outline-offset'             => true,
        'ring-width'                 => true,
        'ring-color'                 => true,
        'ring-offset-width'          => true,
        'ring-offset-color'          => true,
        // Effects
        'box-shadow'                 => true,
        'box-shadow-color'           => true,
        'opacity'                    => true,
        'mix-blend-mode'             => true,
        'background-blend-mode'      => true,
        // Filters
        'blur'                       => true,
        'brightness'                 => true,
        'contrast'                   => true,
        'drop-shadow'                => true,
        'grayscale'                  => true,
        'hue-rotate'                 => true,
        'invert'                     => true,
        'saturate'                   => true,
        'sepia'                      => true,
        'backdrop-blur'              => true,
        'backdrop-brightness'        => true,
        'backdrop-contrast'          => true,
        'backdrop-grayscale'         => true,
        'backdrop-hue-rotate'        => true,
        'backdrop-invert'            => true,
        'backdrop-opacity'           => true,
        'backdrop-saturate'          => true,
        'backdrop-sepia'             => true,
        // Tables
        'border-collapse'            => true,
        'border-spacing'             => true,
        'table-layout'               => true,
        // Transitions & Animation
        'transition-property'        => true,
        'transition-duration'        => true,
        'transition-timing-function' => true,
        'transition-delay'           => true,
        'animation'                  => true,
        // Transforms
        'scale'                      => true,
        'rotate'                     => true,
        'translate'                  => true,
        'skew'                       => true,
        'transform-origin'           => true,
        // Interactivity
        'accent-color'               => true,
        'appearance'                 => true,
        'cursor'                     => true,
        'caret-color'                => true,
        'pointer-events'             => true,
        'resize'                     => true,
        'scroll-behavior'            => true,
        'scroll-margin'              => true,
        'scroll-padding'             => true,
        'scroll-snap-align'          => true,
        'scroll-snap-stop'           => true,
        'scroll-snap-type'           => true,
        'touch-action'               => true,
        'user-select'                => true,
        'will-change'                => true,
        // SVG
        'fill'                       => true,
        'stroke'                     => true,
        'stroke-width'               => true,
        'screen-readers'             => true,
    ],
    'docs'   => [
        '/docs/aspect-ratio',
        '/docs/columns',
        '/docs/break-after',
        '/docs/break-before',
        '/docs/break-inside',
        '/docs/box-decoration-break',
        '/docs/box-sizing',
        '/docs/display',
        '/docs/float',
        '/docs/clear',
        '/docs/isolation',
        '/docs/object-fit',
        '/docs/object-position',
        '/docs/overflow',
        '/docs/overscroll-behavior',
        '/docs/position',
        '/docs/top-right-bottom-left',
        '/docs/visibility',
        '/docs/z-index',
        '/docs/flex-basis',
        '/docs/flex-direction',
        '/docs/flex-wrap',
        '/docs/flex',
        '/docs/flex-grow',
        '/docs/flex-shrink',
        '/docs/order',
        '/docs/grid-template-columns',
        '/docs/grid-column',
        '/docs/grid-template-rows',
        '/docs/grid-row',
        '/docs/grid-auto-flow',
        '/docs/grid-auto-columns',
        '/docs/grid-auto-rows',
        '/docs/gap',
        '/docs/justify-content',
        '/docs/justify-items',
        '/docs/justify-self',
        '/docs/align-content',
        '/docs/align-items',
        '/docs/align-self',
        '/docs/place-content',
        '/docs/place-items',
        '/docs/place-self',
        '/docs/padding',
        '/docs/margin',
        '/docs/space',
        '/docs/width',
        '/docs/min-width',
        '/docs/max-width',
        '/docs/height',
        '/docs/min-height',
        '/docs/max-height',
        '/docs/font-family',
        '/docs/font-size',
        '/docs/font-smoothing',
        '/docs/font-style',
        '/docs/font-weight',
        '/docs/font-variant-numeric',
        '/docs/letter-spacing',
        '/docs/line-height',
        '/docs/list-style-type',
        '/docs/list-style-position',
        '/docs/text-align',
        '/docs/text-color',
        '/docs/text-decoration',
        '/docs/text-decoration-color',
        '/docs/text-decoration-style',
        '/docs/text-decoration-thickness',
        '/docs/text-underline-offset',
        '/docs/text-transform',
        '/docs/text-overflow',
        '/docs/text-indent',
        '/docs/vertical-align',
        '/docs/whitespace',
        '/docs/word-break',
        '/docs/content',
        '/docs/background-attachment',
        '/docs/background-clip',
        '/docs/background-color',
        '/docs/background-origin',
        '/docs/background-position',
        '/docs/background-repeat',
        '/docs/background-size',
        '/docs/background-image',
        '/docs/gradient-color-stops',
        '/docs/border-radius',
        '/docs/border-width',
        '/docs/border-color',
        '/docs/border-style',
        '/docs/divide-width',
        '/docs/divide-color',
        '/docs/divide-style',
        '/docs/outline-width',
        '/docs/outline-color',
        '/docs/outline-style',
        '/docs/outline-offset',
        '/docs/ring-width',
        '/docs/ring-color',
        '/docs/ring-offset-width',
        '/docs/ring-offset-color',
        '/docs/box-shadow',
        '/docs/box-shadow-color',
        '/docs/opacity',
        '/docs/mix-blend-mode',
        '/docs/background-blend-mode',
        '/docs/blur',
        '/docs/brightness',
        '/docs/contrast',
        '/docs/drop-shadow',
        '/docs/grayscale',
        '/docs/hue-rotate',
        '/docs/invert',
        '/docs/saturate',
        '/docs/sepia',
        '/docs/backdrop-blur',
        '/docs/backdrop-brightness',
        '/docs/backdrop-contrast',
        '/docs/backdrop-grayscale',
        '/docs/backdrop-hue-rotate',
        '/docs/backdrop-invert',
        '/docs/backdrop-opacity',
        '/docs/backdrop-saturate',
        '/docs/backdrop-sepia',
        '/docs/border-collapse',
        '/docs/border-spacing',
        '/docs/table-layout',
        '/docs/transition-property',
        '/docs/transition-duration',
        '/docs/transition-timing-function',
        '/docs/transition-delay',
        '/docs/animation',
        '/docs/scale',
        '/docs/rotate',
        '/docs/translate',
        '/docs/skew',
        '/docs/transform-origin',
        '/docs/accent-color',
        '/docs/appearance',
        '/docs/cursor',
        '/docs/caret-color',
        '/docs/pointer-events',
        '/docs/resize',
        '/docs/scroll-behavior',
        '/docs/scroll-margin',
        '/docs/scroll-padding',
        '/docs/scroll-snap-align',
        '/docs/scroll-snap-stop',
        '/docs/scroll-snap-type',
        '/docs/touch-action',
        '/docs/user-select',
        '/docs/will-change',
        '/docs/fill',
        '/docs/stroke',
        '/docs/stroke-width',
        '/docs/screen-readers',
    ],
];
